source 'https://rubygems.org'

gem 'watir-webdriver'
gem 'selenium-webdriver' , '2.45.0'
gem 'activesupport'
gem 'rake'
gem 'rspec'
gem 'allure-rspec', '0.6.4'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'
gem 'rspec-rails'
gem 'watir-dom-wait'
gem 'headless'
gem 'phantomjs'
gem 'faker'
gem 'nokogiri'
#gem 'ruby-gmail'
gem 'gmail'
gem 'ffi'
gem 'taza', :git => 'https://github.com/Rodion13/taza'
gem 'i18n'
gem 'mime'
gem 'mocha', '0.9.3'
gem 'minitest'
gem 'pdf-reader', '~> 1.3.3'
#gem 'cucumber'
#gem "parallel_tests", :group => :development


